### ISSUE TITLE
Misstypo "satured" word

### ISSUE THREAD

**Issue by tskxz** [tskxz/macros4ever#30]
Fix mistype satured to saturated

**Comment by rnihesh** [comment]
Assign me and label as hacktoberfest-accepted

**Comment by rnihesh** [comment]
is the typo only in the food.js

**Comment by tskxz** [comment]
> is the typo only in the food.js

No, you can see here the "satured" word

https://github.com/search?q=repo%3Atskxz%2Fmacros4ever+satured&type=code

**Comment by rnihesh** [comment]
check it and merge
