### ISSUE TITLE
Add more data in foods.js

### ISSUE THREAD

**Issue by tskxz** [tskxz/macros4ever#47]
Add more item foods example with the nutrients information in data/foods.js to be able to populate more into the database while running seeder

**Comment by rnihesh** [comment]
Add me as assigne and label it as hacktoberfest-accepted

**Comment by rnihesh** [comment]
do you want me to add more food data?

**Comment by tskxz** [comment]
> do you want me to add more food data?

Well, you are free up to add more food data, although i was thinking of letting the issue open just in case some other person wants to add more data

**Comment by rnihesh** [comment]
i want it to be completed, so that i can earn my hacktober badge , how much data is it needed ?

**Comment by tskxz** [comment]
> i want it to be completed, so that i can earn my hacktober badge , how much data is it needed ?

Oh fine, I will close now, thanks for clarifying :)

**Comment by rnihesh** [comment]
thank you :)

**Comment by rnihesh** [comment]
if you have any more issues, i'm ready to contribute
